name: basic
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v2
        # execute Cypress using a custom test command
        with:
          # verifies the number of passing tests
          # and passes a variable to Cypress
          # to be read using Cypress.env("lastName")
          command: npm run expect -- --env lastName=Smith
        # when setting "plain" environment variables
        # if we want to pass Cypress to read them
        # we need to prefix them with "CYPRESS_"
        # https://on.cypress.io/environment-variables
        env:
          CYPRESS_firstName: Joe
