name: merge
# run this action on Push and on Pull Request
# to demonstrate the difference in commit message
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: e2e
    steps:
      # you can find all sorts of interesting stuff in the event object
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run on ${{ github.event_name }}
        uses: cypress-io/github-action@v2
        with:
          record: true
          group: merge
          # tag will be either "push" or "pull_request"
          tag: ${{ github.event_name }}
          env: lastName=Smith
        env:
          CYPRESS_firstName: Joe
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # - if the event is push, the title will be undefined
          # and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit
          # message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
