name: separate
on: [push]
# this workflow has two jobs
# 1. the "install-job" installs everything and saves the build
# web application as an upload artifact
# 2. the "test-job" downloads the build site and runs tests
jobs:
  install-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # only install the dependencies without running any tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: npm run build
      # only upload the local folders we built / updated
      #   ./public
      # TIP: we want to avoid uploading node_modules since it is SLOW
      # https://glebbahmutov.com/blog/parallel-cypress-tests-gh-action/
      - name: Save built folders 🆙
        uses: actions/upload-artifact@v2
        with:
          name: built
          path: |
            public

  test-job:
    runs-on: ubuntu-20.04
    needs: install-job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download built folders ⏬
        uses: actions/download-artifact@v4
        with:
          name: built

      # install dependencies and run the tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run expect -- --env lastName=Smith
        env:
          CYPRESS_firstName: Joe
